# kindly generated by appropriated Rails generator
require 'mailjet'
Mailjet.configure do |config|
    config.api_key = 'e680de5f092c3205a3ec428a3f47915c'
    config.secret_key = '16f81943adc03d6f0cc7cdd8f5ca154a'
    config.default_from = 'ouisia.dev.team@gmail.com'
   
    # Mailjet API v3.1 is at the moment limited to Send API.
    # We’ve not set the version to it directly since there is no other endpoint in that version.
    # We recommend you create a dedicated instance of the wrapper set with it to send your emails.
    # If you're only using the gem to send emails, then you can safely set it to this version.
    # Otherwise, you can remove the dedicated line into config/initializers/mailjet.rb.
    config.api_version = 'v3.1'
  end
  